services:
  - type: web
    name: fpl-monthly-league
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FPL_LEAGUE_ID
        value: 754824 